export default {
  state: {
    appendToBody: false,
    autofocus: false,
    bootstrapStyling: false,
    calendarButton: false,
    calendarClass: null,
    clearButton: false,
    dayCellContent: (day) => day.date,
    disabled: false,
    disabledDates: {},
    firstDayOfWeek: 'sun',
    fixedPosition: 'bottom',
    format: 'dd MMM yyyy',
    fullMonthName: false,
    id: null,
    initialView: '',
    inline: false,
    inputClass: null,
    language: 'en',
    maxLength: null,
    maximumView: 'year',
    minimumView: 'day',
    name: null,
    openDate: null,
    pattern: null,
    placeholder: 'Select Date',
    required: false,
    refName: '',
    showEdgeDates: true,
    showHeader: true,
    showCalendarOnFocus: false,
    showCalendarOnButtonClick: false,
    tabindex: null,
    typeable: false,
    useUtc: false,
    value: '',
    wrapperClass: null,
    yearPickerRange: 10,
  },
  getters: {},
  actions: {},
  modules: {},
}
